name: animation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  inview_notifier_list: ^3.0.0
  visibility_detector: ^0.4.0+2
  flutter_vibrate: ^1.3.0
  audioplayers: ^5.2.1
  flutter_card_swiper: ^7.0.1
  flip_card: ^0.7.0
  flutter_custom_clippers: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/files/
    - assets/images/
    - assets/audio/


